title: Zhangir Begim
email: zhanrocks@gmail.com
description: ""
baseurl: ""
url: "https://begim.net"
repository: BegimZhangir/BegimZhangir.github.io
github_username: BegimZhangir

permalink: /blog/:categories/:year/:month/:day/:title/

plugins:
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
